# Generated by Django 3.2.5 on 2021-07-04 00:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0002_auto_20210703_1933'),
    ]

    operations = [
        migrations.RenameField(
            model_name='persona',
            old_name='Domicilio',
            new_name='domicilio',
        ),
    ]
